// Builds the generated half of the Gesso Kit: self-hosted fonts, browser bundles of Pixi/three/rough, icon sets.
// Output goes to kit/ (fonts/, lib/, icons/, fonts.css); hand-written kit files (gesso.css, gesso.mjs) live next to it.
import { build } from 'esbuild';
import { copyFile, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const kit = path.join(root, 'kit');
const require = createRequire(import.meta.url);
const pkg = (name) => path.dirname(require.resolve(`${name}/package.json`));

// family, package, weights. Every font here is OFL-1.1 or Apache-2.0.
const FONTS = [
  ['Cinzel', '@fontsource/cinzel', [400, 700, 900]],
  ['Cinzel Decorative', '@fontsource/cinzel-decorative', [700, 900]],
  ['Grenze Gotisch', '@fontsource/grenze-gotisch', [500, 700, 900]],
  ['Macondo', '@fontsource/macondo', [400]],
  ['Lilita One', '@fontsource/lilita-one', [400]],
  ['Luckiest Guy', '@fontsource/luckiest-guy', [400]],
  ['Fredoka', '@fontsource/fredoka', [400, 600, 700]],
  ['Baloo 2', '@fontsource/baloo-2', [500, 700, 800]],
  ['Orbitron', '@fontsource/orbitron', [500, 700, 900]],
  ['Rajdhani', '@fontsource/rajdhani', [500, 600, 700]],
  ['Press Start 2P', '@fontsource/press-start-2p', [400]],
  ['Pixelify Sans', '@fontsource/pixelify-sans', [400, 700]],
  ['Ma Shan Zheng', '@fontsource/ma-shan-zheng', [400]]
];

async function fonts() {
  const out = path.join(kit, 'fonts');
  await rm(out, { recursive: true, force: true });
  await mkdir(out, { recursive: true });
  let css = '/* Generated by scripts/build-kit.mjs. Fonts: SIL Open Font License 1.1 (Luckiest Guy: Apache-2.0). */\n';
  for (const [family, name, weights] of FONTS) {
    const dir = pkg(name);
    for (const weight of weights) {
      const source = await readFile(path.join(dir, `${weight}.css`), 'utf8').catch(() => '');
      if (!source) continue;
      // keep woff2 only, point at /kit/fonts/
      const rules = source.replace(/src:([^;]+);/g, (_, list) => {
        const woff2 = list.split(',').map((part) => part.trim()).find((part) => part.includes('.woff2'));
        return `src: ${woff2};`;
      });
      for (const match of rules.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)/g)) await copyFile(path.join(dir, 'files', match[1]), path.join(out, match[1]));
      css += rules.replaceAll('url(./files/', 'url(/kit/fonts/').replace(/font-family: '[^']+'/g, `font-family: '${family}'`);
    }
  }
  await writeFile(path.join(kit, 'fonts.css'), css);
}

async function libs() {
  const out = path.join(kit, 'lib');
  await mkdir(out, { recursive: true });
  const bundle = (name, contents) => build({ stdin: { contents, resolveDir: root, loader: 'js' }, bundle: true, format: 'esm', minify: true, target: 'es2022', outfile: path.join(out, name), legalComments: 'eof', logLevel: 'warning' });
  await bundle('pixi.mjs', "export * from 'pixi.js'; export * from 'pixi-filters';");
  await bundle('three.mjs', "export * from 'three'; export { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js'; export { RoundedBoxGeometry } from 'three/examples/jsm/geometries/RoundedBoxGeometry.js'; export { mergeVertices } from 'three/examples/jsm/utils/BufferGeometryUtils.js';");
  await bundle('rough.mjs', "export { default } from 'roughjs';");
}

async function icons() {
  const out = path.join(kit, 'icons');
  await mkdir(out, { recursive: true });
  for (const set of ['game-icons', 'lucide']) await copyFile(path.join(pkg(`@iconify-json/${set}`), 'icons.json'), path.join(out, `${set}.json`));
}

await Promise.all([fonts(), libs(), icons()]);
const size = async (dir) => (await readdir(path.join(kit, dir))).length;
console.log(`kit: ${await size('fonts')} font files, ${await size('lib')} libraries, ${await size('icons')} icon sets`);
